name: Generate release

on:
  pull_request:
  workflow_dispatch:

jobs:

  Compile:
    # needs: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dependences
      run: npm i
    - name: Prepublish
      run: npm run vscode:prepublish
    - name: Package
      run: npm run package

  Release:
    if: github.ref == 'refs/heads/main' && startsWith(github.repository, 'belane/')
    needs: Compile
    runs-on: ubuntu-latest
    
    steps:
    - name: Publish Release (github)
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: "v${{ github.event.inputs.version }}"
        automatic_release_tag: "v${{ github.event.inputs.version }}"
        files: /build/*
